### ISSUE TITLE
Lacking Documentation

### ISSUE THREAD

**Issue by rikez** [EvertonCa/SeleniumSemanticScraper#1]
Hello Everton,

Would you mind providing us a README ?

**Comment by MatheusBordin** [comment]
@EvertonCa Are u looking to that?

**Comment by EvertonCa** [comment]
Will try to make something tomorrow. But keep in mind that the aplication is under development and might change.

**Comment by EvertonCa** [comment]
I made a README file. Feel free to open another issue if something is wrong!
